2022-02-08 08:07:27,288 INFO    MainThread:24009 [wandb_setup.py:_flush():75] Loading settings from /N/u/soodn/Carbonate/.config/wandb/settings
2022-02-08 08:07:27,290 INFO    MainThread:24009 [wandb_setup.py:_flush():75] Loading settings from /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/settings
2022-02-08 08:07:27,290 INFO    MainThread:24009 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-08 08:07:27,290 INFO    MainThread:24009 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'models/5-Deepflash2/DeepFlash2-Train.py', 'program': '/geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/DeepFlash2-Train.py'}
2022-02-08 08:07:27,291 INFO    MainThread:24009 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-08 08:07:27,291 INFO    MainThread:24009 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-08 08:07:27,291 INFO    MainThread:24009 [wandb_init.py:_log_setup():386] Logging user logs to /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/run-20220208_080727-3udg6day/logs/debug.log
2022-02-08 08:07:27,291 INFO    MainThread:24009 [wandb_init.py:_log_setup():387] Logging internal logs to /geode2/home/u090/soodn/Carbonate/ccf-research-kaggle-2021/models/5-Deepflash2/wandb/run-20220208_080727-3udg6day/logs/debug-internal.log
2022-02-08 08:07:27,292 INFO    MainThread:24009 [wandb_init.py:init():420] calling init triggers
2022-02-08 08:07:27,292 INFO    MainThread:24009 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-08 08:07:27,292 INFO    MainThread:24009 [wandb_init.py:init():471] starting backend
2022-02-08 08:07:27,292 INFO    MainThread:24009 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-08 08:07:27,428 INFO    MainThread:24009 [backend.py:ensure_launched():219] starting backend process...
2022-02-08 08:07:27,596 INFO    MainThread:24009 [backend.py:ensure_launched():224] started backend process with pid: 24633
2022-02-08 08:07:27,600 INFO    MainThread:24009 [wandb_init.py:init():480] backend started and connected
2022-02-08 08:07:27,649 INFO    MainThread:24009 [wandb_init.py:init():550] updated telemetry
2022-02-08 08:07:28,153 INFO    MainThread:24009 [wandb_init.py:init():581] communicating current version
2022-02-08 08:07:32,534 INFO    MainThread:24009 [wandb_init.py:init():586] got version response 
2022-02-08 08:07:32,535 INFO    MainThread:24009 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-08 08:07:33,079 INFO    MainThread:24009 [wandb_init.py:init():624] starting run threads in backend
2022-02-08 08:07:37,904 INFO    MainThread:24009 [wandb_run.py:_console_start():1827] atexit reg
2022-02-08 08:07:37,910 INFO    MainThread:24009 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.REDIRECT
2022-02-08 08:07:37,911 INFO    MainThread:24009 [wandb_run.py:_redirect():1706] Redirecting console.
2022-02-08 08:07:37,913 INFO    MainThread:24009 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-08 08:07:37,914 INFO    MainThread:24009 [wandb_init.py:init():651] run started, returning control to user process
2022-02-08 08:07:37,932 INFO    MainThread:24009 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 1
2022-02-08 08:07:37,935 INFO    MainThread:24009 [wandb_run.py:_restore():1769] restore
2022-02-08 08:07:40,429 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 887
  total_bytes: 887
}

2022-02-08 08:07:40,581 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 887
  total_bytes: 887
}

2022-02-08 08:07:41,116 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 887
  total_bytes: 7631
}

2022-02-08 08:07:41,219 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 887
  total_bytes: 7631
}

2022-02-08 08:07:41,321 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7631
  total_bytes: 7631
}

2022-02-08 08:07:41,424 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7631
  total_bytes: 7631
}

2022-02-08 08:07:41,527 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7631
  total_bytes: 7631
}

2022-02-08 08:07:41,630 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7631
  total_bytes: 7631
}

2022-02-08 08:07:41,846 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7631
  total_bytes: 7631
}

2022-02-08 08:07:42,063 INFO    MainThread:24009 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7631
  total_bytes: 7631
}
local_info {
}

2022-02-08 08:07:44,339 INFO    MainThread:24009 [wandb_run.py:_append_files():2194] logging synced files
